name             'apt-osuosl'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/apt-osuosl'
issues_url       'https://github.com/osuosl-cookbooks/apt-osuosl/issues'
license          'Apache-2.0'
chef_version     '>= 16.0'
description      'Installs/Configures apt-osuosl'
version          '2.0.1'

supports         'debian', '~> 9.0'
supports         'debian', '~> 10.0'
supports         'debian', '~> 11.0'
